[package]
name = "xtokens-precompiles"
version = "0.1.0"
authors = ["PureStake"]
edition = "2018"
description = "A Precompile to make xtokens accessible to pallet-evm"

[dependencies]
log = "0.4"
rustc-hex = { version = "2.0.1", default-features = false }
rlp = { version = "0.5", default-features = false }

frame-support = { git = "https://github.com/purestake/substrate", branch = "crystalin-v0.9.9-block-response-length", default-features = false }
evm = { version = "0.30.1", default-features = false, features = ["with-codec"] }
sp-std = { git = "https://github.com/purestake/substrate", branch = "crystalin-v0.9.9-block-response-length", default-features = false }
sp-core = { git = "https://github.com/purestake/substrate", branch = "crystalin-v0.9.9-block-response-length", default-features = false }
sp-runtime = { git = "https://github.com/purestake/substrate", branch = "crystalin-v0.9.9-block-response-length", default-features = false }

pallet-evm = { git = "https://github.com/purestake/frontier", default-features = false, branch = "notlesh-v0.9.9-block-response-length" }
orml-xtokens = { git = "https://github.com/purestake/open-runtime-module-library", default-features = false, branch = "girazoki-v0.9.9-block-response-length" }
frame-system = { git = "https://github.com/purestake/substrate", branch = "crystalin-v0.9.9-block-response-length", default-features = false }
precompile-utils = { path = "../utils", default-features = false }
num_enum = { version = "0.5.3", default-features = false }
xcm = { git = "https://github.com/purestake/polkadot", default-features = false, branch = "notlesh-v0.9.9-block-response-length" }

[dev-dependencies]
serde = "1.0.100"
sp-io = { git = "https://github.com/purestake/substrate", branch = "crystalin-v0.9.9-block-response-length", default-features = false }
derive_more = "0.99"
pallet-balances = { git = "https://github.com/purestake/substrate", branch = "crystalin-v0.9.9-block-response-length", default-features = false }
pallet-timestamp = { git = "https://github.com/purestake/substrate", branch = "crystalin-v0.9.9-block-response-length", default-features = false }
codec = { package = "parity-scale-codec", version = "2.2", default-features = false, features = ["max-encoded-len"] }
cumulus-primitives-core = { git = "https://github.com/purestake/cumulus", branch = "notlesh-nimbus-v0.9.9-block-response-length" }
cumulus-pallet-parachain-system = { git = "https://github.com/purestake/cumulus", branch = "notlesh-nimbus-v0.9.9-block-response-length" }
cumulus-pallet-xcm = { git = "https://github.com/purestake/cumulus", branch = "notlesh-nimbus-v0.9.9-block-response-length" }
pallet-xcm = { git = "https://github.com/purestake/polkadot", branch = "notlesh-v0.9.9-block-response-length" }
xcm-simulator = { git = "https://github.com/purestake/polkadot", branch = "notlesh-v0.9.9-block-response-length" }
xcm-primitives = { path = "../../primitives/xcm/"}
xcm-builder = { git = "https://github.com/purestake/polkadot", branch = "notlesh-v0.9.9-block-response-length" }
xcm-executor = { git = "https://github.com/purestake/polkadot", branch = "notlesh-v0.9.9-block-response-length" }
polkadot-parachain = { git = "https://github.com/purestake/polkadot", branch = "notlesh-v0.9.9-block-response-length" }
[features]
default = ["std"]
std = [
    "frame-support/std",
    "evm/std",
    "sp-std/std",
    "sp-core/std",
    "frame-system/std",
    "precompile-utils/std",
    "pallet-evm/std",
    "orml-xtokens/std",
]
