[package]
name = "xtokens-precompiles"
version = "0.6.0"
authors = ["PureStake"]
edition = "2018"
description = "A Precompile to make xtokens accessible to pallet-evm"

[dependencies]
log = "0.4"
rustc-hex = { version = "2.0.1", default-features = false }

frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", default-features = false }
evm = { version = "0.30.1", default-features = false, features = ["with-codec"] }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.9" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.9" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.9" }

pallet-evm = { git = "https://github.com/purestake/frontier", default-features = false, branch = "polkadot-v0.9.9" }
orml-xtokens = { git = "https://github.com/open-web3-stack/open-runtime-module-library", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.9" }
precompile-utils = { path = "../utils", default-features = false }
num_enum = { version = "0.5.3", default-features = false }
xcm = { git = "https://github.com/paritytech/polkadot", default-features = false, branch = "release-v0.9.9" }

[dev-dependencies]
sha3 = "0.9"
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.9" }
codec = { package = "parity-scale-codec", version = "2.2", default-features = false, features = ["max-encoded-len"] }
sp-runtime = { git="https://github.com/paritytech/substrate", branch="polkadot-v0.9.9" }
pallet-balances = { git="https://github.com/paritytech/substrate", branch="polkadot-v0.9.9" }
pallet-timestamp = { git="https://github.com/paritytech/substrate", branch="polkadot-v0.9.9" }
pallet-scheduler = { git="https://github.com/paritytech/substrate", branch="polkadot-v0.9.9" }
serde = "1.0.100"
derive_more = "0.99"
cumulus-primitives-core = { git = "https://github.com/purestake/cumulus", branch = "nimbus-polkadot-v0.9.9" }
cumulus-pallet-parachain-system = { git = "https://github.com/purestake/cumulus", branch = "nimbus-polkadot-v0.9.9" }
cumulus-pallet-xcm = { git = "https://github.com/purestake/cumulus", branch = "nimbus-polkadot-v0.9.9" }
pallet-xcm = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.9" }
xcm-simulator = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.9" }
xcm-primitives = { path = "../../primitives/xcm/"}
xcm-builder = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.9" }
xcm-executor = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.9" }
polkadot-parachain = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.9" }

[features]
default = ["std"]
std = [
    "frame-support/std",
    "evm/std",
    "sp-std/std",
    "sp-core/std",
    "frame-system/std",
    "precompile-utils/std",
    "pallet-evm/std",
    "orml-xtokens/std",
]
