[package]
name = "perf-test"
version = "0.1.0"
description = "Moonbeam Performance Tests"
authors = ["PureStake"]
edition = "2018"

[dependencies]
log = "0.4.8"
structopt = "0.3.8"

sc-cli = { git = "https://github.com/purestake/substrate", branch = "crystalin-v0.9.9-block-response-length" }
